package com.example.ams.domain.notification;

public enum NotificationType {
	CLASS_NOTICE,
	VIDEO_LESSON,
	HOMEWORK_CREATED,
	HOMEWORK_D1,
	TEST_CREATED,
	TEST_D1,
	CLINIC_CONFIRMED,
	CLINIC_SLOT_CHANGED,
	HOMEWORK_RESULT,
	TEST_RESULT,
	CLINIC_RESULT,
	ENROLLMENT_ASSIGNED,
	DILIGENCE_REPORT
}
